const datos = [
  {
    id: 1,
    title: "Curso HTML",
    description: "Curso de HTML desde cero[completo]",
    body: "Ut tincidunt tincidunt erat. Sed cursus turpis vitae tortor. Quisque malesuada placerat nisl. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem.",
    prize: "139",
    learn: "Learn how to edit a video Interview",
    Requirements: "No video editinf or Premiere Pro Knowledge is necessary",
    muestra: true,
    imgUrl:
      "https://uploads-ssl.webflow.com/635a453bdfb49358830950bd/635a463a9c53141574eedda6_template_imagen_curso.jpg",
  },
  {
    id: 2,
    title: "Curso Javascript",
    description: "Curso de Javascript Nivel JR",
    body: "Aenean ut eros et nisl sagittis vestibulum. Donec posuere vulputate arcu. Proin faucibus arcu quis ante. Curabitur at lacus ac velit ornare lobortis. ",
    prize: "200",
    learn: "Learn how to edit a video Interview",
    Requirements: "No video editinf or Premiere Pro Knowledge is necessary",
    muestra: true,
    imgUrl: "https://astwellsoft.com/assets/images/blog/javascript.jpg",
  },
  {
    id: 3,
    title: "Estructura de Datos",
    description: "Estructura de datos para iniciantes",
    body: "Phasellus ullamcorper ipsum rutrum nunc. Nullam quis ante. Etiam ultricies nisi vel augue. Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc.",
    prize: "180",
    learn: "Learn how to edit a video Interview",
    Requirements: "No video editinf or Premiere Pro Knowledge is necessary",
    muestra: true,
    imgUrl: "https://img-b.udemycdn.com/course/480x270/1693748_4c8f.jpg",
  },
  {
    id: 4,
    title: "Derivadas",
    description: "Derivadas de 0 a 100",
    body: "Aenean ut eros et nisl sagittis vestibulum. Donec posuere vulputate arcu. Proin faucibus arcu quis ante. Curabitur at lacus ac velit ornare lobortis. ",
    prize: "149",
    learn: "Learn how to edit a video Interview",
    Requirements: "No video editinf or Premiere Pro Knowledge is necessary",
    muestra: true,
    imgUrl:
      "https://cursosgratis.com.mx/wp-content/uploads/2022/01/que-es-y-para-que-sirven-las-derivadas-1024x576-1.jpeg",
  },
  {
    id: 5,
    title: "Curso Python",
    description: "Python para principiantes",
    body: "Phasellus ullamcorper ipsum rutrum nunc. Nullam quis ante. Etiam ultricies nisi vel augue. Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc.",
    prize: "250",
    learn: "Learn how to edit a video Interview",
    Requirements: "No video editinf or Premiere Pro Knowledge is necessary",
    muestra: true,
    imgUrl: "https://i.ytimg.com/vi/chPhlsHoEPo/maxresdefault.jpg",
  },
  {
    id: 6,
    title: "Adobe Photoshop",
    description: "Curso de Photoshop de 0 a 100",
    body: "Aenean ut eros et nisl sagittis vestibulum. Donec posuere vulputate arcu. Proin faucibus arcu quis ante. Curabitur at lacus ac velit ornare lobortis. ",
    prize: "155",
    learn: "Learn how to edit a video Interview",
    Requirements: "No video editinf or Premiere Pro Knowledge is necessary",
    muestra: true,
    imgUrl: "https://i.ytimg.com/vi/4gw9KyEJ0BI/maxresdefault.jpg",
  },
  {
    id: 7,
    title: "Curso Android",
    description: "Crea tu primera aplicacion android(Nivel Junior)",
    body: "Phasellus ullamcorper ipsum rutrum nunc. Nullam quis ante. Etiam ultricies nisi vel augue. Aenean tellus metus, bibendum sed, posuere ac, mattis non, nunc.",
    prize: "129",
    learn: "Learn how to edit a video Interview",
    Requirements: "No video editinf or Premiere Pro Knowledge is necessary",
    muestra: true,
    imgUrl:
      "https://losmejorescursosde.com/wp-content/uploads/2021/02/desarrollo-android.jpg",
  },
];

export default datos;
